## Hello Python!

How to write code in python...
lets start

### For Comments 

We use "#" for comments in python

### Print statement or python  looks like as Calculator

In [4]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# How much is your $100 worth after 7 years?
print(100*1.1**7)

10
0
15
5.0
4
16
194.87171000000012


## Variables and Types

 A Python variable is a reserved memory location to store values.
 Python sets the variable type based on the value that is assigned to it.
- x = 10
- y=9

In [6]:
# Create a variable savings

savings=100

# Print out savings
print(savings)

100


100

### Calculations

In [10]:
# calculate Area of Triangle
base = 10.0
height = 22.1
Area = 0.5*(base * height)
Area

110.5

110.5

### Types

In [11]:
X = 2
type(X)

int

int

In [13]:
Y = True
type(Y)

bool

bool

In [14]:
Z = 8.9
type(Z)

float

float

In [16]:
A = 2+3j
type(A)

complex

complex

### Type Conversion

In [17]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" +str( savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


### Problem

- Each variable represents single value.
- Data Science: Many data points.
- eg: Heights of the Family

In [19]:
h1 = 2.3
h2 = 3.2
h3 = 3.5

- This is inconvenient way

## Python has special built-in-function 'list'

In [22]:
[2.3,3.2,3.5]

[2.3, 3.2, 3.5]

In [23]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas


List = [hall,kit,liv,bed,bath,]
# Print areas
print(List)


[11.25, 18.0, 20.0, 10.75, 9.5]


In [24]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway",hall, "kitchen",kit, "living room",liv,  "bedroom",bed,"bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


### List of Lists

In [25]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom",bed],
         ["bathroom",bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))


[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>

### Slicing and Dicing

In [1]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


### Addition of inside elements of list

In [26]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


28.75

In [27]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs= areas[0:6]
# Use slicing to create upstairs
upstairs = areas[6:10]


# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


### List Manipulation 

- Change list elements
- Add list elements 
- Remove list elements

In [31]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1]= 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]

In [2]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ['poolhouse',24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ['garage',15.45]

print(areas_1)
print(areas_2)


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


## Functions

- piece of reuseable code

In [32]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1

print(type(var1))
# Print out length of var1

print(len(var1))
# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


In [33]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


[20.0, 18.0, 11.25, 10.75, 9.5]

### Methods

In [39]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0

print(areas.index(20.0))
# Print out how often 9.50 appears in areas

print(areas.count(9.50))


2
1


In [40]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)

areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


## One More Method

# Result : Packages
Directory of Python Scripts.
Each script = module
Specify functions, methods,types.
Thousands of packages available.
- Numpy
- Matplotlib
- Scikit-learn


### Install package
- Download get-pip.py
- Terminal:
- python3 get-pip.py
- pip3 install numpy

In [44]:
import  numpy as np
np.array([2,3])

array([2, 3])

array([2, 3])

In [45]:
# lets solve maths problem 
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2 * r *math.pi

# Calculate A
A = math.pi *r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [46]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


40317.10572106901

- #### Below I'm Using Numpy, but not very clear

In [47]:
from numpy import array

fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]

fam_ext = fam + ["me", 1.79]

print(str(len(fam_ext)) + " elements in fam_ext")

np_fam = array(fam_ext)
print(np_fam)

10 elements in fam_ext
['liz' '1.73' 'emma' '1.68' 'mom' '1.71' 'dad' '1.89' 'me' '1.79']


- #### Recomended method to import & use packages

In [48]:
import numpy as np

fam = ["liz", 1.73,"emma", 1.68,"mom", 1.71,"dad", 1.89]

fam_ext = fam + ["me", 1.79]

print(str(len(fam_ext)) + " elements in fam_ext")

np_fam = np.array(fam_ext)
print(np_fam)

10 elements in fam_ext
['liz' '1.73' 'emma' '1.68' 'mom' '1.71' 'dad' '1.89' 'me' '1.79']


In [50]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))
print(np_baseball)

<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


### 2D Numpy Array

In [51]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball =np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


## Data Analysis

- Get to know about data 

### Basic Statistics 

In [59]:
arr = [2.2,1.2,11.2,22]
np.mean(arr)

9.15

9.15

In [60]:
arr = [2.2,1.2,11.2,22]
np.median(arr)

6.699999999999999

6.699999999999999

In [61]:
arr = [2.2,1.2,11.2,22]
np.std(arr)

8.378991586103902

8.378991586103902

In [62]:
arr = [2.2,1.2,11.2,22]
np.corrcoef(arr)

1.0

1.0